name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
          bun-version: latest
    - name: Install TS library deps
      run: bun i --cwd react_plug_ts
    - name: Build TS code
      run: bun run --cwd react_plug_ts build
    - name: Build example plug-in
      run: cargo xtask bundle example
